services:
  ziscar_db:
    image: &postgres postgres:16
    container_name: ziscar_db
    env_file: 
      - path: .env
        required: false
    restart: ${RESTART_POLICY:-no}
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  test_ziscar_db:
    image: *postgres
    container_name: test_ziscar_db
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_admin
      - POSTGRES_DB=test_ziscar
    ports:
      - "9862:5432"
    volumes:
      - test-db-data:/var/lib/postgresql/data

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: ziscar_frontend
    ports:
      - "5173:5173"

  backend_dev:
    build:
      context: .
      dockerfile: backend.Dockerfile
      args:
        - APP_ENV=dev
    container_name: ziscar_backend_dev
    env_file: 
      - path: .env
        required: false
    environment:
      - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@ziscar_db:5432/${DB_NAME}?schema=public
    depends_on:
      - ziscar_db
    ports:
      - "3000:3000"

  backend_prod:
    build:
      context: .
      dockerfile: backend.Dockerfile
      args:
        - APP_ENV=prod
    container_name: ziscar_backend_prod
    restart: always
    ports:
      - "3000:3000"

volumes:
  db-data:
  test-db-data:
