version: "3.8"
services:
  ziscar_db:
    image: postgres:16
    container_name: ziscar_db
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  test_ziscar_db:
    image: postgres:16
    container_name: test_ziscar_db
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${TEST_DB_USERNAME}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}
    ports:
      - "${TEST_DB_PORT}:5432"
    volumes:
      - test-db-data:/var/lib/postgresql/data

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: ../backend.Dockerfile
  #   container_name: nest_backend
  #   restart: always
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: postgres://user:password@postgres:5432/mydb
  #   ports:
  #     - "3000:3000"

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: ../frontend.Dockerfile
  #   container_name: react_frontend
  #   restart: always
  #   depends_on:
  #     - backend
  #   ports:
  #     - "3001:3001"

volumes:
  db-data:
  test-db-data:
